CREATE TABLE CLIENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (100),
    CPF VARCHAR(11)
);

CREATE TABLE PRODUCT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR (100),
    UNIT_PRICE NUMERIC(20,2)
);

CREATE TABLE ORDER(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENT INTEGER REFERENCES CLIENT(ID),
    ORDER_DATA TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ORDER_ITEM(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES PEDIDO(ID),
    PRODUTO_ID INTEGER REFERENCES PEDIDO(ID),
    QUANTIDADE INTEGER
);

CREATE TABLE USER(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
)
